add pathing checks for aggregateCIDR.pl
Signed-off-by: Nic Boet <nic@boet.cc>

diff --git a/postwhite b/postwhite
--- a/postwhite
+++ b/postwhite
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /usr/bin/env bash
 #
 ###################################################################
 # Postwhite - Automatic Postcreen allowlist / denylist Generator #
@@ -59,6 +59,16 @@ reject_line_v6="${reject_line_v4}"
 
 # Abort script on error (FYI: enabling will cause script to exit silently if mailer has no valid results)
 set -e
+
+if [ -f /usr/local/bin/aggregateCIDR.pl ]; then
+    aggregateCIDR='/usr/local/bin/aggregateCIDR.pl'
+elif [ which aggregateCIDR.pl ]; then
+    aggregateCIDR=$(which aggregateCIDR.pl)
+else
+    echo "fatal: unable to locate aggregateCIDR.pl"
+    echo "https://github.com/nabbi/route-summarization"
+    exit 1
+fi
 
 printf "Starting Postwhite v$version ($lastupdated)\n"
 
@@ -270,11 +280,11 @@ fi
 printf "\nCIDR and Host summarization...\n"
 # the depends on https://github.com/nabbi/route-summarization with symlink in system PATH
 # invalid hosts are also screened and removed
-sed '/\./s/\/32//g' "${tmp1}" | sort -u | aggregateCIDR.pl --quiet --spf > "${tmp2}" &
+sed '/\./s/\/32//g' "${tmp1}" | sort -u | ${aggregateCIDR} --quiet --spf > "${tmp2}" &
 show_dots "$!"
 
 if [ x"$enable_denylist" = x"yes" ] ; then
-        cat "${denytmp1}" | sort -u | aggregateCIDR.pl --quiet --spf > "${denytmp2}" &
+        cat "${denytmp1}" | sort -u | ${aggregateCIDR} --quiet --spf > "${denytmp2}" &
         show_dots "$!"
 fi
 
diff --git a/scrape_yahoo b/scrape_yahoo
--- a/scrape_yahoo
+++ b/scrape_yahoo
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /usr/bin/env bash
 
 #########################################################################
 # Scrape Yahoo! - Generates a list of Yahoo! Outbound IPs for Postwhite #
@@ -20,6 +20,16 @@ yahoo_url="https://senders.yahooinc.com/outbound-mail-servers"
 
 # Abort script on error
 set -e
+
+if [ -f /usr/local/bin/aggregateCIDR.pl ]; then
+    aggregateCIDR='/usr/local/bin/aggregateCIDR.pl'
+elif [ which aggregateCIDR.pl ]; then
+    aggregateCIDR=$(which aggregateCIDR.pl)
+else
+    echo "fatal: unable to locate aggregateCIDR.pl"
+    echo "https://github.com/nabbi/route-summarization"
+    exit 1
+fi
 
 printf "Scraping Yahoo! outbound IP addresses...\n"
 
@@ -55,14 +65,14 @@ fi
 ipv4_mailers=$(echo "$content" | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/([0-9]{1,3}?)' | while read line; do echo "ip4:$line"; done)
 
 # Overwrite old Yahoo! mailer list with scraped IPv4 hosts
-echo "$ipv4_mailers" | aggregateCIDR.pl --quiet --spf > "$yahoo_static_hosts"
+echo "$ipv4_mailers" | ${aggregateCIDR} --quiet --spf > "$yahoo_static_hosts"
 
 # Scrape and format IPv6 addresses
 # This isn't parsing the page correctly. Post filter through aggregateCIDR.pl to clean invalids
 ipv6_mailers=$(echo "$content" | grep -E -o '(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))' | while read line; do echo "ipv6:$line"; done)
 
 # Append IPv6 hosts to newly-created Yahoo! mailer list
-echo "$ipv6_mailers" | aggregateCIDR.pl --quiet --spf  >> "$yahoo_static_hosts"
+echo "$ipv6_mailers" | ${aggregateCIDR} --quiet --spf  >> "$yahoo_static_hosts"
 
 printf '\nVerizon/AOL/Yahoo! outbound mailers updated.\n'
 
