add postmap path checks
Signed-off-by: Nic Boet <nic@boet.cc>

diff --git a/postwhite b/postwhite
--- a/postwhite
+++ b/postwhite
@@ -70,6 +70,15 @@ else
     exit 1
 fi
 
+if [ -f /usr/sbin/postmap ]; then
+    postmap='/usr/sbin/postmap'
+elif [ which postmap ]; then
+    postmap=$(which postmap)
+else
+	echo "fatal: unable to locate postmap"
+	exit 1
+fi
+
 printf "Starting Postwhite v$version ($lastupdated)\n"
 
 # Check for passed config file
@@ -321,13 +330,13 @@ fi
 printf "\nWriting $numrules allowlist rules to ${postfixpath}/${allowlist}...\n"
 printf "# allowlist generated by Postwhite v$version on $(date)\n# https://github.com/stevejenkins/postwhite/\n# $numrules total rules\n" > "${postfixpath}"/"${allowlist}"
 cat "${tmp5}" >> "${postfixpath}"/"${allowlist}"
-postmap "${postfixpath}"/"${allowlist}"
+${postmap} "${postfixpath}"/"${allowlist}"
 
 if [ x"$enable_denylist" = x"yes" ] ; then
 	printf "\nWriting $numdenyrules denylist rules to ${postfixpath}/${denylist}...\n"
 	printf "# denylist generated by Postwhite v$version on $(date)\n# https://github.com/stevejenkins/postwhite/\n# $numdenyrules total rules\n" > "${postfixpath}"/"${denylist}"
 	cat "${denytmp5}" >> "${postfixpath}"/"${denylist}"
-	postmap "${postfixpath}"/"${denylist}"
+	${postmap} "${postfixpath}"/"${denylist}"
 fi
 
 # Remove temp files
